### ISSUE TITLE
MAPA MENTAL

### ISSUE THREAD

**Issue by RicardoMtzSts** [SistemasTecTlaxiaco/mapa-mental-RicardoMtzSts#2]
[Mapa mental.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-RicardoMtzSts/files/7267860/Mapa.mental.pdf)

**Comment by lourdeshernandez2003** [comment]
18% tomando en cuenta todo los puntos de nos pide la rubrica.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
